# Generated by Django 3.2.21 on 2023-09-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230924_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='overall_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
