# Generated by Django 3.2.21 on 2023-10-05 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productsize_sizecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.sizecategory'),
        ),
    ]
