# Generated by Django 3.2.21 on 2023-10-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_size_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizecategory',
            options={'verbose_name_plural': 'Size categories'},
        ),
    ]
